#!/bin/tcsh -f
# Copyright (c) 2023 Matheus Garcia.  All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer. 
# 
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution. 
# 
# 3. Neither the name of the author nor the names of its contributors may be
#    used to endorse or promote products derived from this software without
#    specific prior written permission. 
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
# AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
# OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
# DAMAGE.

if ( ! "$?0" ) then
  echo 'You may only run this script by explicitly calling its file.'
  exit -1
endif

if ( ! "$?main" ) then
  if ( "$1" == ) then
    echo 'Enter a username to verify.'
    exit -1
  endif
  alias function 'set argv = ( \!* ) ; source "$main"'

  set main = "$0"
  set followers = "`function listing '$1' followers`"
  set following = "`function listing '$1' following`"

  @ count = ( 1 )
  while ( "$count" <= "$#following" )
    ( function verify "$following[$count]" )
    @ count++
  end
  exit
endif
goto "$1" ; shift

listing:
@ count = ( 1 )
while ( 1 )
  set ret = "`wget -O - 'https://github.com/$1?tab=$2&page=$count' | grep -o '/users/.*/hovercard' | uniq | sed 's/\/users\///;s/\/hovercard//'`"

  if ( "$ret" == ) exit

  foreach user ( $ret )
    echo "$user"
  end
  @ count++
end

verify:
foreach user ( $followers )
  if ( "$user" == "$1" ) exit
end

echo "$1 doesn't follow you back."
exit 1
